baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Research Journal - Junior Seminar 580'
theme = "paper"

[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "hugo v0.110.0+extended darwin/amd64 BuildDate=unknown"

disqusShortname = 'River Magee'   # use disqus comments

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'YOUR_GITHUB_ID'                 # github.com/YOUR_GITHUB_ID
  instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  rss = true                                # show rss icon

  # home page profile
  avatar = '/images/River_Magee_Headshot.jpg'                 # gravatar email or image url
  name = 'River Magee'
  bio = 'Junior, Integrative Informatics Major'


  # misc
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
